-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 21:09:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema pharm_db_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharm_db_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharm_db_project` DEFAULT CHARACTER SET utf8 ;
USE `pharm_db_project` ;

-- -----------------------------------------------------
-- Table `pharm_db_project`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`customer` (
  `customer_id` INT NOT NULL,
  `insurance_policy` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharm_db_project`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`product` (
  `product_id` INT NOT NULL,
  `stock` INT ZEROFILL NOT NULL,
  `price` FLOAT NOT NULL,
  `name` VARCHAR(45) NULL,
  `schedule` INT ZEROFILL NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharm_db_project`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`supplier` (
  `supplier_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`supplier_id`),
  CONSTRAINT `suppplier_product`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `pharm_db_project`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharm_db_project`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`order` (
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_order_idx` (`customer_id` ASC) INVISIBLE,
  CONSTRAINT `customer_order`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pharm_db_project`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharm_db_project`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`order_item` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `content_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `pharm_db_project`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `pharm_db_project`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharm_db_project`.`restock_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`restock_request` (
  `transaction_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `stock_supplier_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `product_request`
    FOREIGN KEY (`product_id`)
    REFERENCES `pharm_db_project`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stock_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `pharm_db_project`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharm_db_project`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharm_db_project`.`transaction` (
  `transaction_id` INT NOT NULL,
  `change` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  `net` FLOAT NOT NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
